version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    command: npm run start
    depends_on:
      - mysql
    restart: always
    environment:
      DB_HOSTNAME: mysql
      MYSQL_USER: books_user
      MYSQL_DATABASE: bookshop
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - app-network

  migration:
    build:
      context: .
    command: bash -c "cd ./build && ls && chmod +x ./run_migrations.sh && ./run_migrations.sh"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: books_user
      MYSQL_DATABASE: bookshop
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
