version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    command: npm run start
    depends_on:
      - mysql-development
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - app-network

  mysql-development:
    image: mysql:5
    container_name: mysql-development
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: books_user
      MYSQL_DATABASE: bookshop
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql-development
    ports:
      - "3306:3306"
    networks:
      - app-network

  mysql-test:
    image: mysql:5
    container_name: mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: books_user
      MYSQL_DATABASE: bookshop
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql-test
    ports:
      - "3307:3306"
    networks:
      - app-network

  dev-migrations:
    build:
      context: .
    command: bash -c "cd ./build && ls && chmod +x ./run_migrations.sh && ./run_migrations.sh dev"
    links:
      - mysql-development
    depends_on:
      - mysql-development
    networks:
      - app-network

  test-migrations:
    build:
      context: .
    command: bash -c "cd ./build && ls && chmod +x ./run_migrations.sh && ./run_migrations.sh test"
    links:
      - mysql-test
    depends_on:
      - mysql-test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
